import { Link } from "@tanstack/react-router";
import { ArrowLeft, CheckCircle2, ChevronDown, Clock3, Crosshair, RotateCcw, Target, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { getReadingTest } from "@/data/readingTests";
import { loadAttempts, normalise } from "./storage";

export function ReviewPage({attemptId}:{attemptId:string}){
 const attempt=loadAttempts().find(a=>a.id===attemptId); const test=attempt?getReadingTest(attempt.testId):undefined; const [open,setOpen]=useState<number[]>([]); const [evidence,setEvidence]=useState("");
 const breakdown=useMemo(()=>{if(!attempt||!test)return[];return (["tfng","gap","matching","mcq"] as const).map(type=>{const qs=test.questions.filter(q=>q.type===type);const right=qs.filter(q=>normalise(attempt.answers[q.id]||"")===normalise(q.answer)).length;return {type,label:{tfng:"True / False",gap:"Completion",matching:"Matching",mcq:"Multiple choice"}[type],right,total:qs.length}})},[attempt,test]);
 if(!attempt||!test)return <div className="grid min-h-screen place-items-center bg-background p-6 text-center"><div><h1 className="text-2xl font-bold">Attempt not found</h1><Button asChild className="mt-5"><Link to="/history/reading_test">View my attempts</Link></Button></div></div>;
 const accuracy=Math.round(attempt.score/attempt.total*100); const mins=Math.floor(attempt.durationSeconds/60); const secs=attempt.durationSeconds%60;
 return <div className="min-h-screen bg-question"><header className="border-b bg-background"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4 sm:px-6"><Button asChild variant="ghost" size="icon"><Link to="/reading"><ArrowLeft/></Link></Button><div><p className="text-xs text-muted-foreground">Review attempt</p><p className="font-semibold">{test.title}</p></div><Button asChild variant="outline" className="ml-auto"><Link to="/reading/test/$testId" params={{testId:test.id}}><RotateCcw/>Retake</Link></Button></div></header>
 <main><section className="border-b bg-background"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><span className="text-xs font-bold uppercase text-brand">Test complete</span><h1 className="mt-2 text-3xl font-bold">Your Reading result</h1><p className="mt-2 text-muted-foreground">Review every answer and return to the exact passage evidence.</p></div><div className="flex items-end gap-3"><span className="text-6xl font-bold text-brand">{attempt.band.toFixed(1)}</span><span className="pb-2 text-sm text-muted-foreground">Estimated band</span></div></div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric icon={<CheckCircle2/>} label="Raw score" value={`${attempt.score}/${attempt.total}`}/><Metric icon={<Target/>} label="Accuracy" value={`${accuracy}%`}/><Metric icon={<Clock3/>} label="Time spent" value={`${mins}:${String(secs).padStart(2,"0")}`}/><Metric icon={<Crosshair/>} label="Needs focus" value={breakdown.sort((a,b)=>a.right/a.total-b.right/b.total)[0]?.label||"—"}/></div><div className="mt-6 flex flex-wrap gap-4">{breakdown.map(x=><div key={x.type} className="text-xs text-muted-foreground"><strong className="text-foreground">{x.label}</strong> {x.right}/{x.total}</div>)}</div></div></section>
 <section className="mx-auto grid max-w-7xl gap-0 border-x bg-background lg:grid-cols-2"><div className="max-h-[calc(100vh-5rem)] overflow-y-auto border-r p-6 lg:sticky lg:top-0 lg:p-9"><p className="text-xs font-bold uppercase text-brand">Reading Passage {test.part}</p><h2 className="mt-3 text-3xl font-bold">{test.passageTitle}</h2><p className="mt-2 text-sm italic text-muted-foreground">{test.passageSubtitle}</p><div className="mt-7 space-y-5 leading-7">{test.paragraphs.map(p=><p key={p.label} className={evidence&&p.text.toLowerCase().includes(evidence.toLowerCase().slice(0,25))?"rounded-md bg-success-soft p-3 ring-1 ring-success":""}><strong className="mr-3">{p.label}</strong>{p.text}</p>)}</div></div><div className="p-4 sm:p-7">{test.questions.map(q=>{const value=attempt.answers[q.id]||"No answer";const right=normalise(value)===normalise(q.answer);const expanded=open.includes(q.id);return <article key={q.id} className={`mb-4 rounded-md border bg-card p-4 ${right?"border-success/40":"border-destructive/40"}`}><div className="flex gap-3">{right?<CheckCircle2 className="mt-0.5 size-5 shrink-0 text-success"/>:<XCircle className="mt-0.5 size-5 shrink-0 text-destructive"/>}<div className="min-w-0 flex-1"><p className="text-sm font-semibold">{q.id}. {q.prompt}</p><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><p className={`rounded-md p-2 ${right?"bg-success-soft text-success":"bg-destructive-soft text-destructive"}`}>Your answer: <strong>{value}</strong></p>{!right&&<p className="rounded-md bg-success-soft p-2 text-success">Correct answer: <strong>{q.answer}</strong></p>}</div><Button variant="ghost" size="sm" className="mt-3 px-0" onClick={()=>setOpen(x=>expanded?x.filter(id=>id!==q.id):[...x,q.id])}>Explanation & passage evidence <ChevronDown className={`transition ${expanded?"rotate-180":""}`}/></Button>{expanded&&<div className="mt-2 border-t pt-3 text-sm"><p>{q.explanation}</p><blockquote className="mt-2 border-l-2 border-brand pl-3 italic text-muted-foreground">“{q.evidence}”</blockquote><Button variant="outline" size="sm" className="mt-3" onClick={()=>setEvidence(q.evidence)}><Crosshair/>Locate in passage</Button></div>}</div></div></article>})}</div></section></main></div>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-md border bg-card p-4"><div className="flex items-center gap-2 text-muted-foreground [&_svg]:size-4">{icon}<span className="text-xs font-medium">{label}</span></div><p className="mt-2 text-xl font-bold">{value}</p></div>}
