import { useNavigate } from "@tanstack/react-router";
import { Bookmark, ChevronLeft, Clock3, Eraser, Eye, EyeOff, Flag, Highlighter, Pause, Play, Send } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import type { ReadingQuestion, ReadingTest } from "@/data/readingTests";
import { bandFrom, clearDraft, loadDraft, normalise, saveAttempt, saveDraft } from "./storage";

type Props={test:ReadingTest};
export function TestPlayer({test}:Props){
 const navigate=useNavigate();
 const [answers,setAnswers]=useState<Record<number,string>>({});
 const [flags,setFlags]=useState<number[]>([]); const [remaining,setRemaining]=useState(test.duration*60); const [paused,setPaused]=useState(false); const [showSeconds,setShowSeconds]=useState(true); const [font,setFont]=useState<"S"|"M"|"L">("M"); const [left,setLeft]=useState(50); const [note,setNote]=useState(""); const [highlight,setHighlight]=useState(""); const started=useRef(Date.now());
 useEffect(()=>setAnswers(loadDraft(test.id)),[test.id]);
 useEffect(()=>{if(Object.keys(answers).length)saveDraft(test.id,answers)},[answers,test.id]);
 useEffect(()=>{if(paused)return;const timer=window.setInterval(()=>setRemaining(r=>Math.max(0,r-1)),1000);return()=>clearInterval(timer)},[paused]);
 const submit=()=>{const score=test.questions.filter(q=>normalise(answers[q.id]||"")===normalise(q.answer)).length;const id=`${test.id}-${Date.now()}`;saveAttempt({id,testId:test.id,testTitle:test.title,submittedAt:new Date().toISOString(),answers,score,total:test.questions.length,band:bandFrom(score,test.questions.length),durationSeconds:Math.round((Date.now()-started.current)/1000)});clearDraft(test.id);navigate({to:"/reading/review/$attemptId",params:{attemptId:id}})};
 useEffect(()=>{if(remaining===0)submit()},[remaining]);
 const onSelect=()=>{const value=window.getSelection()?.toString().trim();if(value)setHighlight(value)};
 const startResize=(event:React.PointerEvent)=>{event.preventDefault();const move=(e:PointerEvent)=>setLeft(Math.max(30,Math.min(70,e.clientX/window.innerWidth*100)));const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 const display=showSeconds?`${String(Math.floor(remaining/60)).padStart(2,"0")}:${String(remaining%60).padStart(2,"0")}`:`${Math.ceil(remaining/60)} min`;
 return <div className="flex h-screen flex-col overflow-hidden bg-background">
  <header className="flex min-h-16 flex-wrap items-center gap-3 border-b bg-background px-3 py-2 sm:px-5"><Button variant="ghost" size="icon" onClick={()=>navigate({to:"/reading"})} aria-label="Back to reading tests"><ChevronLeft/></Button><div className="min-w-40"><p className="text-xs text-muted-foreground">IELTS Academic · Reading</p><p className="text-sm font-semibold">Passage {test.part}</p></div><div className="order-3 mx-auto flex w-full items-center justify-center gap-1 sm:order-none sm:w-auto"><Button variant="ghost" size="icon" onClick={()=>setPaused(!paused)} aria-label={paused?"Resume timer":"Pause timer"}>{paused?<Play/>:<Pause/>}</Button><div className="flex w-24 items-center justify-center gap-2 font-mono text-lg font-bold"><Clock3 className="size-4 text-brand"/>{display}</div><Button variant="ghost" size="icon" onClick={()=>setShowSeconds(!showSeconds)} aria-label="Toggle seconds">{showSeconds?<EyeOff/>:<Eye/>}</Button></div><div className="ml-auto flex items-center gap-1"><div className="hidden rounded-md border p-0.5 sm:flex">{(["S","M","L"] as const).map(x=><Button key={x} size="sm" variant={font===x?"secondary":"ghost"} className="h-7 px-2" onClick={()=>setFont(x)}>{x}</Button>)}</div><Button variant="ghost" size="icon" onClick={()=>{setHighlight("");setNote("")}} aria-label="Clear highlight and notes"><Eraser/></Button><Button onClick={submit}><Send/>Submit<span className="hidden sm:inline"> test</span></Button></div></header>
  <div className="relative flex min-h-0 flex-1 flex-col md:flex-row">
   <section style={{width:`${left}%`}} className="exam-pane hidden shrink-0 overflow-y-auto border-r p-6 md:block lg:p-10" onMouseUp={onSelect}><div className="mx-auto max-w-2xl"><p className="text-xs font-bold uppercase text-brand">Reading Passage {test.part}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">You should spend about 20 minutes on Questions 1–{test.questions.length}, which are based on the passage below.</p><h1 className="mt-8 text-3xl font-bold">{test.passageTitle}</h1><p className="mt-2 text-sm italic text-muted-foreground">{test.passageSubtitle}</p><div className={`mt-8 space-y-6 leading-8 ${font==="S"?"text-sm":font==="L"?"text-lg":"text-base"}`}>{test.paragraphs.map(p=><p key={p.label}><strong className="mr-3">{p.label}</strong><span className={highlight&&p.text.includes(highlight)?"bg-highlight":undefined}>{p.text}</span></p>)}</div></div></section>
   <div onPointerDown={startResize} className="group hidden w-1 cursor-col-resize bg-border transition hover:bg-brand md:block"><span className="absolute top-1/2 -ml-2 h-10 w-5 rounded-full border bg-background"/></div>
   <section className="exam-pane min-w-0 flex-1 overflow-y-auto bg-question p-4 pb-24 sm:p-7 sm:pb-24"><div className="mx-auto max-w-3xl"><div className="mb-6 rounded-md border bg-card p-4 md:hidden"><h2 className="font-bold">{test.passageTitle}</h2><p className="mt-1 text-sm text-muted-foreground">Passage is shown beside the questions on larger screens.</p></div>{test.questions.map((q,index)=><Question key={q.id} question={q} value={answers[q.id]||""} flagged={flags.includes(q.id)} onFlag={()=>setFlags(f=>f.includes(q.id)?f.filter(x=>x!==q.id):[...f,q.id])} onChange={value=>setAnswers(a=>({...a,[q.id]:value}))} showHeader={index===0||test.questions[index-1].group!==q.group}/>)}</div></section>
   {highlight&&<aside className="absolute bottom-20 left-5 z-20 w-80 rounded-md border bg-popover p-3 shadow-xl"><div className="flex items-center gap-2 text-sm font-semibold"><Highlighter className="size-4 text-warning"/>Highlighted text</div><p className="mt-2 line-clamp-2 text-xs text-muted-foreground">{highlight}</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note…" className="mt-3 h-16 w-full resize-none rounded-md border bg-background p-2 text-xs"/><Button variant="ghost" size="sm" className="mt-1" onClick={()=>setHighlight("")}>Close</Button></aside>}
  </div>
  <footer className="flex h-14 shrink-0 items-center gap-2 overflow-x-auto border-t bg-background px-4"><div className="mr-2 flex items-center gap-2 text-xs font-semibold"><Bookmark className="size-4"/>Part {test.part}</div>{test.questions.map(q=><Button key={q.id} variant={answers[q.id]?"default":"outline"} size="icon" className={`relative size-8 shrink-0 text-xs ${flags.includes(q.id)?"ring-2 ring-warning":""}`} onClick={()=>document.getElementById(`question-${q.id}`)?.scrollIntoView({behavior:"smooth"})}>{q.id}</Button>)}</footer>
 </div>
}
function Question({question,value,onChange,flagged,onFlag,showHeader}:{question:ReadingQuestion;value:string;onChange:(v:string)=>void;flagged:boolean;onFlag:()=>void;showHeader:boolean}){
 return <div>{showHeader&&<div className="mb-4 mt-3 rounded-md border bg-card p-4"><h2 className="font-bold">{question.group}</h2><p className="mt-1 text-sm text-muted-foreground">{question.instruction}</p></div>}<article id={`question-${question.id}`} className="mb-3 scroll-mt-5 rounded-md border bg-card p-4"><div className="flex gap-3"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-foreground text-xs font-bold text-background">{question.id}</span><div className="min-w-0 flex-1"><p className="text-sm font-medium leading-6">{question.prompt}</p>{question.type==="gap"?<input value={value} onChange={e=>onChange(e.target.value)} placeholder="Type your answer" className="mt-3 h-10 w-full max-w-sm rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"/>:<div className="mt-3 flex flex-wrap gap-2">{question.options?.map(option=><Button key={option} variant={value===option?"default":"outline"} size="sm" onClick={()=>onChange(option)}>{option}</Button>)}</div>}</div><Button variant="ghost" size="icon" onClick={onFlag} aria-label={`Flag question ${question.id}`} className={flagged?"text-warning":"text-muted-foreground"}><Flag className={flagged?"fill-current":""}/></Button></div></article></div>
}
